image: ubuntu:18.04

before_script:
  - apt update && apt install python3-pip
  - pip install -r requirements.txt
  - pip install pyinstaller

cache:
 paths:
   - dist/

stages:
  - build


.BuildPackage:
  stage: build
  artifacts:
    paths:
      - dist/main
    expire_in: 1 week

Package:
  extends: .BuildPackage
  script:
      - pyinstaller main.py -w --onefile

