image: python:3.7-slim

before_script:
  - apt update && apt install -y python3-pip python3-venv

cache:
 paths:
   - dist/

stages:
  - build


.BuildPackage:
  stage: build
  artifacts:
    paths:
      - dist/main
    expire_in: 1 week

Package:
  extends: .BuildPackage
  script:
      - python3 -m venv venv && . ./venv/bin/activate && pip3 install -r requirements.txt && pip3 install setuptools wheel
      - pyinstaller main.py -w --onefile

