image: ubuntu:20.04

before_script:
  - apt update && apt install -y python3-pip
  - pip3 install -r requirements.txt

cache:
 paths:
   - dist/

stages:
  - build


.BuildPackage:
  stage: build
  artifacts:
    paths:
      - dist/main
    expire_in: 1 week

Package:
  extends: .BuildPackage
  script:
      - pyinstaller main.py -w --onefile

